### ISSUE TITLE
ArticlesListView

### ISSUE THREAD

**Issue by Tarek-D** [LinFeiLong/sublimfood#10]
![Image](https://github.com/LinFeiLong/sublimfood/assets/51507642/8b160423-3da5-49b6-b9c2-831364bb514b)

**Comment by Tarek-D** [comment]
![Image](https://github.com/LinFeiLong/sublimfood/assets/51507642/0eae33fb-ab9f-4e65-a3a9-7a2f4459c8f0)

**Comment by LinFeiLong** [comment]
Le scroll ne fonctionne pas, et passe sous le titre

**Comment by LinFeiLong** [comment]
- Scroll vertical de la vue
- Scroll horizontal des cartes.

Regarder ArticleView comme exemple
