### ISSUE TITLE
IngredientCard

### ISSUE THREAD

**Issue by riindaa** [LinFeiLong/sublimfood#9]
![Image](https://github.com/LinFeiLong/sublimfood/assets/86025903/72f90782-0d4c-4f06-a6ba-1b25fd80eaa7)

![Image](https://github.com/LinFeiLong/sublimfood/assets/86025903/a9cd6f70-4c85-4f3b-8c1e-415aa66a2dbb)

![Image](https://github.com/LinFeiLong/sublimfood/assets/86025903/562d5bd7-aef7-4168-970a-970bc8f5df7d)

**Comment by LinFeiLong** [comment]
Ajout du link
